### PR TITLE
fix: framework support

### PR DESCRIPTION
**Pull request by coolsoftwaretyler**
Reopening https://github.com/dominicstop/react-native-ios-context-menu/pull/117, which got kind of messed up in some rebasing.

This will:

1. [x] Add more checks for different pod install configurations [like we did in `react-native-ios-utilities`](https://github.com/coolsoftwaretyler/react-native-ios-context-menu/commit/2c8a1bdff3a11ba45264ac0b0162efc51ee88da6)
2. [x] Fix import paths

### CODE REVIEW

**Comment by dominicstop** [comment]
run-workflow:build-example-ios-for-pr

**Comment by dominicstop** [comment]
run-workflow:build-example-ios-for-pr

**Comment by dominicstop** [comment]
run-workflow:build-example-ios-for-pr

**Comment by dominicstop** [comment]
run-workflow:build-example-ios-for-pr

**Comment by dominicstop** [comment]
run-workflow:build-example-ios-for-pr

**Comment by dominicstop** [comment]
run-workflow:build-example-ios-for-pr

**Comment by dominicstop** [comment]
run-workflow:build-example-ios-for-pr

**Comment by dominicstop** [comment]
run-workflow:build-example-ios-for-pr

**Comment by dominicstop** [comment]
run-workflow:build-example-ios-for-pr

**Comment by dominicstop** [comment]
run-workflow:build-example-ios-for-pr

**Comment by coolsoftwaretyler** [comment]
Ah interesting. I tested this from a patch on my own app so I didn't try the example app in this library.

What are you using Reanimated for in the example? If it's not critical, maybe we can remove it and simplify the example app as a test ground.

**Comment by coolsoftwaretyler** [comment]
The Reanimated failure seems related to this: https://github.com/software-mansion/react-native-reanimated/issues/6062

It looks like 5aeff10e90204d4a0d29b24d175ed3934604ef9d fixes the headers by using relative imports, so I might close this PR out if that works for you. I can open up another PR and see if I can fix reanimated in the example app.

**Comment by dominicstop** [comment]
hello, sorry for the delayed response;  the ithub action for testing the diff. builds just stopped working recently, and i haven't been able to fix it yet.

i have reverted my changes, in favor of your fixes. i am currently waiting for all the build variants to complete; thank you for your patience.

**Pull request merged**
